# Generated by Django 5.1.3 on 2025-04-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_categoryinteraction_productinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('monetary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('view_count', models.IntegerField(default=0)),
                ('cart_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('most_preferred_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
    ]
