# Generated by Django 5.1.3 on 2025-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartinteraction_favoriteinteraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstats',
            name='behavioral_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerstats',
            name='recommended_categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstats',
            name='rfm_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
