# Generated by Django 5.1.3 on 2025-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstats',
            name='rfm_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
