# Generated by Django 5.1.3 on 2025-05-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customerstats_rfm_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstats',
            name='rfm_label',
        ),
    ]
