# Generated by Django 5.1.3 on 2025-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_customerstats_rfm_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstats',
            name='discounted_monetary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
