# Generated by Django 5.1.3 on 2025-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinteraction',
            name='discounted_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
